# Generated by Django 3.1.3 on 2021-08-20 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moveevent',
            name='position',
        ),
        migrations.RemoveField(
            model_name='moveevent',
            name='previous_position',
        ),
        migrations.AddField(
            model_name='moveevent',
            name='new_x',
            field=models.IntegerField(default=0, verbose_name='New X'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moveevent',
            name='new_y',
            field=models.IntegerField(default=0, verbose_name='New Y'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moveevent',
            name='old_x',
            field=models.IntegerField(default=0, verbose_name='Old X'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moveevent',
            name='old_y',
            field=models.IntegerField(default=0, verbose_name='Old Y'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tank',
            name='x',
            field=models.IntegerField(default=0, verbose_name='Position X'),
        ),
        migrations.AddField(
            model_name='tank',
            name='y',
            field=models.IntegerField(default=0, verbose_name='Position Y'),
        ),
        migrations.AlterField(
            model_name='tank',
            name='player',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='map.player', verbose_name='Player'),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
