# Generated by Django 3.1.3 on 2021-08-23 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20210820_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='ad_vote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.player', verbose_name='Daily Vote for this dead player'),
        ),
    ]
