# Generated by Django 3.1.3 on 2021-08-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20210823_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='logs_channel',
            field=models.BigIntegerField(default=879390962282029146, verbose_name='Logs channel ID'),
            preserve_default=False,
        ),
    ]
