# Generated by Django 3.2.6 on 2022-05-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_game_guild_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='guild_icon_url',
            field=models.URLField(default='https://cdn.discordapp.com/icons/869906440268173333/94df287f32e8f7e5496f0df4c6c8048c.webp', verbose_name='Guild Icon URL'),
            preserve_default=False,
        ),
    ]
