# Generated by Django 3.2.6 on 2023-05-14 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_auto_20230512_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteEvent',
            fields=[
                ('baseevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='map.baseevent')),
                ('new_range', models.IntegerField(verbose_name='New Range')),
                ('receiving_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiving_player_set', to='map.player', verbose_name='Player receiving vote')),
                ('voting_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_player_set', to='map.player', verbose_name='Voting Player')),
            ],
            bases=('map.baseevent',),
        ),
    ]
