# Generated by Django 3.2.6 on 2023-05-20 00:11

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_remove_voteevent_new_range'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='baseevent',
            managers=[
                ('logs', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='moveevent',
            managers=[
                ('logs', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='rangeupgradeevent',
            managers=[
                ('logs', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='shootevent',
            managers=[
                ('logs', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='transferevent',
            managers=[
                ('logs', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='voteevent',
            managers=[
                ('logs', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='next_vote_target',
            field=models.IntegerField(default=3),
        ),
    ]
